<?php

return [
    // أيقونات الأدوية والصيدليات
    'medications' => [
        ['icon' => 'pills', 'label' => 'حبوب'],
        ['icon' => 'tablet', 'label' => 'أقراص دواء'],
        ['icon' => 'capsules', 'label' => 'كبسولات'],
        ['icon' => 'prescription-bottle', 'label' => 'زجاجة دواء'],
        ['icon' => 'prescription-bottle-medical', 'label' => 'زجاجة دواء طبية'],
        ['icon' => 'syringe', 'label' => 'سرنجة'],
        ['icon' => 'vial', 'label' => 'قارورة دواء'],
        ['icon' => 'flask', 'label' => 'قارورة مخبرية'],
        ['icon' => 'test-tube', 'label' => 'أنبوب اختبار'],
        ['icon' => 'microscope', 'label' => 'ميكروسكوب'],
        ['icon' => 'dna', 'label' => 'حمض نووي'],
        ['icon' => 'thermometer', 'label' => 'ميزان حرارة'],
        ['icon' => 'stethoscope', 'label' => 'سماعة طبيب'],
        ['icon' => 'heart-pulse', 'label' => 'نبض'],
        ['icon' => 'file-medical', 'label' => 'ملف طبي'],
        ['icon' => 'notes-medical', 'label' => 'ملاحظات طبية'],
        ['icon' => 'truck-medical', 'label' => 'سيارة إسعاف'],
        ['icon' => 'hospital', 'label' => 'مستشفى'],
        ['icon' => 'clinic-medical', 'label' => 'عيادة طبية'],
        ['icon' => 'house-chimney-medical', 'label' => 'رعاية منزلية'],
        ['icon' => 'kit-medical', 'label' => 'حقيبة إسعاف'],
        ['icon' => 'shield-virus', 'label' => 'درع ضد الفيروسات'],
        ['icon' => 'lungs', 'label' => 'رئة'],
        ['icon' => 'bone', 'label' => 'عظم'],
        ['icon' => 'tooth', 'label' => 'سن'],
        ['icon' => 'eye', 'label' => 'عين'],
        ['icon' => 'ear', 'label' => 'أذن'],
        ['icon' => 'hand', 'label' => 'يد'],
        ['icon' => 'foot', 'label' => 'قدم'],
    ],
    
    // أيقونات مستحضرات التجميل
    'cosmetics' => [
        ['icon' => 'face-smile', 'label' => 'وجه مبتسم'],
        ['icon' => 'face-grin', 'label' => 'وجه ضاحك'],
        ['icon' => 'face-laugh', 'label' => 'وجه مبتسم'],
        ['icon' => 'spoon', 'label' => 'ملعقة مكياج'],
        ['icon' => 'spray-can', 'label' => 'رذاذ'],
        ['icon' => 'bottle-droplet', 'label' => 'قطارة'],
        ['icon' => 'jar', 'label' => 'مرطبان'],
        ['icon' => 'box', 'label' => 'علبة'],
        ['icon' => 'palette', 'label' => 'بالت مكياج'],
        ['icon' => 'brush', 'label' => 'فرشاة'],
        ['icon' => 'scissors', 'label' => 'مقص'],
        ['icon' => 'comb', 'label' => 'مشط'],
        ['icon' => 'soap', 'label' => 'صابون'],
        ['icon' => 'shower', 'label' => 'دش'],
        ['icon' => 'bath', 'label' => 'حمام'],
        ['icon' => 'sink', 'label' => 'حوض'],
        ['icon' => 'toilet-paper', 'label' => 'ورق تواليت'],
        ['icon' => 'hands-bubbles', 'label' => 'غسيل اليدين'],
        ['icon' => 'hand-sparkles', 'label' => 'يد لامعة'],
        ['icon' => 'sparkles', 'label' => 'لمعان'],
        ['icon' => 'star', 'label' => 'نجمة'],
        ['icon' => 'heart', 'label' => 'قلب'],
        ['icon' => 'gem', 'label' => 'جوهرة'],
        ['icon' => 'crown', 'label' => 'تاج'],
        ['icon' => 'fire-flame-curved', 'label' => 'لهب'],
        ['icon' => 'droplet', 'label' => 'قطرة'],
        ['icon' => 'water', 'label' => 'ماء'],
        ['icon' => 'leaf', 'label' => 'ورقة'],
        ['icon' => 'seedling', 'label' => 'بذرة'],
        ['icon' => 'flower', 'label' => 'زهرة'],
        ['icon' => 'sun', 'label' => 'شمس'],
        ['icon' => 'moon', 'label' => 'قمر'],
    ],
    
    // أيقونات المستلزمات الطبية
    'medical-supplies' => [
        ['icon' => 'scissors', 'label' => 'مقص'],
        ['icon' => 'syringe', 'label' => 'سرنجة'],
        ['icon' => 'vial', 'label' => 'قارورة'],
        ['icon' => 'flask', 'label' => 'قارورة مخبرية'],
        ['icon' => 'test-tube', 'label' => 'أنبوب اختبار'],
        ['icon' => 'microscope', 'label' => 'ميكروسكوب'],
        ['icon' => 'wheelchair', 'label' => 'كرسي متحرك'],
        ['icon' => 'bone', 'label' => 'عظم'],
        ['icon' => 'hand', 'label' => 'يد'],
        ['icon' => 'eye', 'label' => 'عين'],
        ['icon' => 'ear', 'label' => 'أذن'],
        ['icon' => 'tooth', 'label' => 'سن'],
        ['icon' => 'lungs', 'label' => 'رئة'],
        ['icon' => 'heart', 'label' => 'قلب'],
        ['icon' => 'brain', 'label' => 'دماغ'],
        ['icon' => 'dna', 'label' => 'حمض نووي'],
        ['icon' => 'shield-virus', 'label' => 'درع ضد الفيروسات'],
        ['icon' => 'user-nurse', 'label' => 'ممرضة'],
        ['icon' => 'user-doctor', 'label' => 'طبيب'],
        ['icon' => 'thermometer', 'label' => 'ميزان حرارة'],
        ['icon' => 'stethoscope', 'label' => 'سماعة طبيب'],
        ['icon' => 'kit-medical', 'label' => 'حقيبة إسعاف'],
        ['icon' => 'truck-medical', 'label' => 'سيارة إسعاف'],
        ['icon' => 'hospital', 'label' => 'مستشفى'],
        ['icon' => 'clinic-medical', 'label' => 'عيادة'],
    ],
    
    // أيقونات الخدمات الطبية
    'services' => [
        ['icon' => 'user-doctor', 'label' => 'طبيب'],
        ['icon' => 'user-nurse', 'label' => 'ممرضة'],
        ['icon' => 'tooth', 'label' => 'أسنان'],
        ['icon' => 'eye', 'label' => 'عين'],
        ['icon' => 'prescription-bottle', 'label' => 'صيدلي'],
        ['icon' => 'hospital', 'label' => 'مستشفى'],
        ['icon' => 'clinic-medical', 'label' => 'عيادة'],
        ['icon' => 'house-chimney-medical', 'label' => 'رعاية منزلية'],
        ['icon' => 'truck-medical', 'label' => 'سيارة إسعاف'],
        ['icon' => 'phone', 'label' => 'هاتف'],
        ['icon' => 'envelope', 'label' => 'بريد'],
        ['icon' => 'message', 'label' => 'رسالة'],
        ['icon' => 'comment', 'label' => 'تعليق'],
        ['icon' => 'video', 'label' => 'فيديو'],
        ['icon' => 'camera', 'label' => 'كاميرا'],
    ],
    
    // أيقونات الصحة والعافية
    'health' => [
        ['icon' => 'heart', 'label' => 'القلب'],
        ['icon' => 'heart-pulse', 'label' => 'نبض القلب'],
        ['icon' => 'brain', 'label' => 'الدماغ'],
        ['icon' => 'lungs', 'label' => 'الرئتان'],
        ['icon' => 'bone', 'label' => 'العظام'],
        ['icon' => 'tooth', 'label' => 'الأسنان'],
        ['icon' => 'eye', 'label' => 'العين'],
        ['icon' => 'ear', 'label' => 'الأذن'],
        ['icon' => 'hand', 'label' => 'اليد'],
        ['icon' => 'foot', 'label' => 'القدم'],
        ['icon' => 'leaf', 'label' => 'ورقة'],
        ['icon' => 'seedling', 'label' => 'بذرة'],
        ['icon' => 'droplet', 'label' => 'قطرة ماء'],
    ],
    
    // أيقونات الأجهزة الطبية
    'devices' => [
        ['icon' => 'microscope', 'label' => 'ميكروسكوب'],
        ['icon' => 'vial', 'label' => 'قارورة'],
        ['icon' => 'flask', 'label' => 'قارورة مخبرية'],
        ['icon' => 'test-tube', 'label' => 'أنبوب اختبار'],
        ['icon' => 'heart-pulse', 'label' => 'نبض'],
        ['icon' => 'brain', 'label' => 'دماغ'],
        ['icon' => 'eye', 'label' => 'عين'],
        ['icon' => 'ear', 'label' => 'أذن'],
        ['icon' => 'tooth', 'label' => 'سن'],
        ['icon' => 'bone', 'label' => 'عظم'],
        ['icon' => 'thermometer', 'label' => 'ميزان حرارة'],
        ['icon' => 'stethoscope', 'label' => 'سماعة طبيب'],
        ['icon' => 'syringe', 'label' => 'سرنجة'],
        ['icon' => 'wheelchair', 'label' => 'كرسي متحرك'],
        ['icon' => 'kit-medical', 'label' => 'حقيبة إسعاف'],
        ['icon' => 'truck-medical', 'label' => 'سيارة إسعاف'],
        ['icon' => 'hospital', 'label' => 'مستشفى'],
        ['icon' => 'clinic-medical', 'label' => 'عيادة'],
    ],
    
    // أيقونات الدعم والخدمة
    'support' => [
        ['icon' => 'phone', 'label' => 'هاتف'],
        ['icon' => 'envelope', 'label' => 'بريد'],
        ['icon' => 'message', 'label' => 'رسالة'],
        ['icon' => 'comment', 'label' => 'تعليق'],
        ['icon' => 'chat', 'label' => 'دردشة'],
        ['icon' => 'handshake', 'label' => 'مصافحة'],
        ['icon' => 'thumbs-up', 'label' => 'موافق'],
        ['icon' => 'star', 'label' => 'نجمة'],
        ['icon' => 'heart', 'label' => 'قلب'],
        ['icon' => 'tag', 'label' => 'وسم'],
        ['icon' => 'globe', 'label' => 'كرة أرضية'],
        ['icon' => 'map', 'label' => 'خريطة'],
        ['icon' => 'location-dot', 'label' => 'موقع'],
        ['icon' => 'building', 'label' => 'مبنى'],
        ['icon' => 'shop', 'label' => 'متجر'],
        ['icon' => 'truck', 'label' => 'شاحنة'],
    ],
    
    // أيقونات التجارة والتسوق
    'commerce' => [
        ['icon' => 'tag', 'label' => 'وسم'],
        ['icon' => 'shop', 'label' => 'متجر'],
        ['icon' => 'building', 'label' => 'مبنى'],
        ['icon' => 'truck', 'label' => 'شاحنة'],
    ],
    
    // أيقونات الابتكار والبحث
    'innovation' => [
        ['icon' => 'microscope', 'label' => 'ميكروسكوب'],
        ['icon' => 'flask', 'label' => 'قارورة مخبرية'],
        ['icon' => 'test-tube', 'label' => 'أنبوب اختبار'],
        ['icon' => 'vial', 'label' => 'قارورة'],
        ['icon' => 'dna', 'label' => 'حمض نووي'],
        ['icon' => 'brain', 'label' => 'دماغ'],
        ['icon' => 'satellite', 'label' => 'قمر صناعي'],
        ['icon' => 'signal', 'label' => 'إشارة'],
        ['icon' => 'wifi', 'label' => 'واي فاي'],
        ['icon' => 'cloud', 'label' => 'سحابة'],
        ['icon' => 'server', 'label' => 'خادم'],
        ['icon' => 'database', 'label' => 'قاعدة بيانات'],
        ['icon' => 'desktop', 'label' => 'كمبيوتر مكتبي'],
    ],
];
